### ISSUE TITLE
Minor issues after the new data setup

### ISSUE THREAD

**Issue by jmillanacosta** [NanoCommons/erm-database#12]
- [x] The example ERM link in the about page needs to be updated to `/substance/erm/ERM*` (https://nanocommons.github.io/erm-database/about/)
- [x] Similarly, need to update the links for ERM tags in post pages (e.g. https://nanocommons.github.io/erm-database/2023/08/29/nanosolveit-identifiers.html)

**Comment by egonw** [comment]
I think both are fixed now. Plz reopen if there are remaining issues (or create new issues).
