### ISSUE TITLE
add JavaScript depiction of nanomaterials

### ISSUE THREAD

**Issue by egonw** [NanoCommons/erm-database#7]
ping @larsgw

- [x] identify which info the JavaScript needs
- [x] add support for the fields in the `/substance/` template
- [x] integrate the JavaScript integration

**Comment by larsgw** [comment]
> identify which info the JavaScript needs

Any combination of core, coating, and shell. Takes in labels and fill colors & patterns.

**Comment by larsgw** [comment]
https://www.npmjs.com/package/nanoviz-svg

**Comment by egonw** [comment]
@larsgw, maybe something we can look at this afternoon?

**Comment by egonw** [comment]
Finally added:

![image](https://github.com/NanoCommons/erm-database/assets/26721/00e3ecea-0a17-4e4b-a9ae-2fe499f345ff)

**Comment by egonw** [comment]
The syntax is limited at this moment but can be extended later:

```yaml
nanoviz:
  - label: Ag
  - label: PVP
```
